language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

php:
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_script:
    - composer install

script:
    -  ./vendor/bin/phpunit tests

git:
  depth: 5
