language: php

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_script:
    - composer install

script:
    -  ./vendor/bin/phpunit tests

git:
  depth: 5
